name: CI/CD - Push na main + deploy Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: wesley2019/order-api
      DOCKER_TAG: '1.0'

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v3

      - name: ⚙️ Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 🔁 Restore dependências
        run: dotnet restore FastTechFoods.Orders.sln

      - name: 🛠️ Build da aplicação
        run: dotnet build FastTechFoods.Orders.sln --configuration Release --no-restore

      - name: 🐳 Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏗️ Build da imagem Docker com tag
        run: docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

      - name: 🚀 Push da imagem para o Docker Hub
        run: docker push $DOCKER_IMAGE:$DOCKER_TAG

      - name: 🔐 Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ⚙️ Obter credenciais do AKS
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.AZURE_AKS_CLUSTER }} --overwrite-existing
      - name: 🚀 Aplicar manifestos no cluster Kubernetes (recursivo)
        run: kubectl apply -R -f ./k8s/

      - name: 🔍 Verificar deployments no namespace fase5
        run: kubectl get deployments -n fase5

      - name: 🔄 Reiniciar o deployment (forçar update da imagem)
        run: kubectl rollout restart deployments/order-api -n fase5
