apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fase5
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080