apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: fase5
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
