apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-cardapio-pvc
  namespace: fase5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
